# Generated by Django 4.1.2 on 2022-11-14 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppNotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='etiqueta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppNotas.etiqueta'),
        ),
    ]
